# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-16 03:52
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField(help_text='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_location', django.contrib.gis.db.models.fields.PointField(blank=True, editable=False, null=True, srid=4326)),
                ('last_location_date_time', models.DateTimeField(blank=True, editable=False, null=True)),
                ('update_id', models.IntegerField(editable=False, unique=True)),
            ],
        ),
    ]
