# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 14:31
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, null=True)),
                ('area', django.contrib.gis.db.models.fields.GeometryField(help_text='If a polygon is used nodes of this layer will have to be contained in it.If a point is used nodes of this layer can be located anywhere. Lines are not allowed.', srid=4326)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='profiles.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
